#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                  

# Global Configs
[config]
version_check = false

# Templates

#swww
[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "any", "--transition-fps", "60"]
set = true

# Kitty
[templates.kitty]
input_path = '~/.config/matugen/templates/matugen-kitty.conf'
output_path = '~/.config/kitty/matugen/colors-matugen.conf'
post_hook = 'pkill -USR1 kitty'
# Bat
[templates.bat]
input_path = '~/.config/matugen/templates/matugen-bat-colors.tmTheme'
output_path = '~/.config/bat/themes/matugen-bat-colors.tmTheme'
post_hook = 'bat cache --build' 

# Spicetify
[templates.spicetify]
input_path = '~/.config/matugen/templates/spotify-colors.ini'
output_path = '~/.config/spicetify/Themes/Comfy/color.ini'

# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/matugen-rofi.rasi'
output_path = '~/.config/rofi/matugen/matugen-rofi.rasi'

# Hyprland
[templates.hyprland]
input_path = '~/.config/matugen/templates/matugen-hyprland.conf'
output_path = '~/.config/hypr/matugen/matugen-hyprland.conf'

# Hyprlock
[templates.hyprlock]
input_path = '~/.config/matugen/templates/matugen-hyprlock.conf'
output_path = '~/.config/hypr/hyprlock/matugen/matugen-hyprlock.conf'

# Waybar
#[templates.waybar]
#input_path = '~/.config/matugen/templates/matugen-waybar.css'
#output_path = '~/.config/waybar/matugen/matugen-waybar.css'
#post_hook = 'pkill -SIGUSR2 waybar'

# Gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

# Gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# Qt5
[templates.qt5]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen-qt5ct.conf'

# Qt6
[templates.qt6]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen-qt6ct.conf'

# Kvantum
[templates.kvantum]
input_path = '~/.config/matugen/templates/matugen.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

# Cava
[templates.cava]
input_path = '~/.config/matugen/templates/matugen-cava'
output_path = '~/.config/cava/config'
post_hook = 'pkill -USR1 cava'

# Pywalfox
[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

# Zathura
[templates.zathura]
input_path = '~/.config/matugen/templates/matugen-zathurarc'
output_path = '~/.config/zathura/zathurarc'

# Ferdium
[templates.ferdium]
input_path = '~/.config/matugen/templates/ferdium-matugen.json'
output_path = '~/.config/Ferdium/config/settings.json'

# Discord
[templates.discord]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/BetterDiscord/themes/matugen.theme.css'

# Sherlock
[template.sherlock]
input_path = '~/.config/matugen/templates/matugen-sherlock.css'
output_path = '~/.config/sherlock/main.css'
# Wlogout
[templates.wlogout]
input_path = '~/.config/matugen/templates/matugen-wlogout.css'
output_path = '~/.config/wlogout/theme.css'
